<a href="https://colab.research.google.com/github/Feliz-ua/goit-math-hw-01/blob/main/goit_math_hw_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Завдання №1 Робота з зображеннями як з матрицями (аналітичний розв'язок)**

- - -

Дано матрицю зображення $M$ та матрицю накладеного ефекту $E$:

$$
M = \begin{pmatrix}
100 & 150 & 200 \\
50 & 100 & 150 \\
0 & 50 & 100
\end{pmatrix}, \quad
E = \begin{pmatrix}
20 & 30 & 40 \\
10 & 20 & 30 \\
5 & 10 & 15
\end{pmatrix}
$$

**Необхідно реалізувати три алгоритми обробки:**

***1. Зміна контрасту.*** Необхідно зменшити яскравість зображення
$M$. Це множення матриці на скаляр (число) λ. Кожен елемент матриці множиться на це число 0.5

***2. Корекція яскравості.***
Це додавання скаляра $c$ до матриці $M$. Число додається до кожного елемента матриці. Додайте до зображення $M$ число 25. Це збільшить яскравість кожного пікселя на 25.

***3. Змішування (Blending).***
Ми створюємо нове зображення, змішуючи оригінал та ефект у певній пропорції. Для цього створи нове зображення як лінійну комбінацію: $0.8 \cdot $M + 0.2⋅E. Це імітує прозорість ефекту.

- - -

**Рішення:**
- - -
**Алгоритм 1. Зміна контрасту (contrast)**

Зменшуємо яскравість зображення $M$ шляхом множення на скаляр $\lambda = 0.5$.
$$M_{contrast} = 0.5 \cdot M$$

Обчислення:

$M_{11}= $$100 \cdot 0.5 = 50.$

$M_{12}= $$150 \cdot 0.5 = 75.$

$M_{13}= $$200 \cdot 0.5 = 100.$

$M_{21}= $$50 \cdot 0.5 = 25.$

$M_{22}= $$100 \cdot 0.5 = 50.$

$M_{23}= $$150 \cdot 0.5 = 75.$

$M_{31}= $$0 \cdot 0.5 = 0.$

$M_{32}= $$50 \cdot 0.5 = 25.$

$M_{33}= $$100 \cdot 0.5 = 50.$


Отже отримкємо нову матрицю зі зниженим наполовину контрастом $M$:
$$
M_{contrast} = \begin{pmatrix}
50 & 75 & 100 \\
25 & 50 & 75 \\
0 & 25 & 50
\end{pmatrix}$$

**Алгоритм 2. Корекція яскравості (brightness)**

Додамо скаляр $c=25$ до кожного елементу матриці $M$:

$$ M_{brightness}=M+25 $$

Обчислення:

$M_{11}= $$100 + 25 = 125$

$M_{12}= $$150 + 25 = 175.$

$M_{13}= $$200 + 25 = 225.$

$M_{21}= $$50 +25  = 75.$

$M_{22}= $$100 + 25 = 125.$

$M_{23}= $$150 + 25 = 175.$

$M_{31}= $$0 + 25 = 25.$

$M_{32}= $$50 +25 = 75.$

$M_{33}= $$100 +25 = 125.$


Отже отримкємо нову матрицю зі зниженим наполовину контрастом $M$:
$$
M_{brightness} = \begin{pmatrix}
125 & 175 & 225 \\
75 & 125 & 175 \\
25 & 75 & 125
\end{pmatrix}$$

**Алгоритм 3. Змішування (Blending)**

Знайдемо лінійну комбінацію за формулою: $0.8 \cdot M + 0.2 \cdot E$.

Обчислюємо матрицю $08 \cdot M$:
$$
0.8 \cdot M = \begin{pmatrix}
100 & 150 & 200 \\
50 & 100 & 150 \\
0 & 50 & 100
\end{pmatrix}= \begin{pmatrix}
80 & 120 & 160 \\
40 & 80 & 120 \\
0 & 40 & 80
\end{pmatrix}$$

Також обчислюємо матрицю $02 \cdot E$:

$$
0.2 \cdot E = \begin{pmatrix}
20 & 30 & 40 \\
10 & 20 & 30 \\
5 & 10 & 15
\end{pmatrix}=\begin{pmatrix}
4 & 6 & 8 \\
2 & 4 & 6 \\
1 & 2 & 3
\end{pmatrix}
$$

Додамо результати поелементно:

$$
\begin{pmatrix}
80 & 120 & 160 \\
40 & 80 & 120 \\
0 & 40 & 80
\end{pmatrix}+\begin{pmatrix}
4 & 6 & 8 \\
2 & 4 & 6 \\
1 & 2 & 3
\end{pmatrix}
$$


Результат змішування:

$$
M_{blending}=\begin{pmatrix}
84 & 126 & 168 \\
42 & 84 & 126 \\
1 & 42 & 83
\end{pmatrix}
$$









In [ ]:
#Завдання 1. Робота з зображеннями як з матрицями
#Програмна реалізація

import numpy as np

# --- Вхідні дані ---

# Створення матриці зображення M
M = np.array([
    [100, 150, 200],
    [50, 100, 150],
    [0, 50, 100]
])

# Створення матриці ефекту E
E = np.array([
    [20, 30, 40],
    [10, 20, 30],
    [5, 10, 15]
])

print("--- Матриця зображень M ---")
print(M)
print("\n--- Матриця ефекту E ---")
print(E)

# --- Реалізація алгоритмів ---

# 1. Зміна контрасту (Множення на скаляр)
# Ми просто множимо матрицю на число, NumPy робить це для кожного елемента автоматично.
lambda_val = 0.5
contrast_M = M * lambda_val

print("\n\n=== 1. Зміна контрасту (M * 0.5) ===")
print(contrast_M)


# 2. Корекція яскравості (Додавання скаляра)
# Додаємо число до матриці.
c = 25
brightness_M = M + c

print("\n\n=== 2. Корекція яскравості (M + 25) ===")
print(brightness_M)


# 3. Змішування (Blending)
# Лінійна комбінація двох матриць.
blend_M = (0.8 * M) + (0.2 * E)

print("\n\n=== 3. Змішування (0.8*M + 0.2*E) ===")
print(blend_M)

--- Оригінальна матриця M ---
[[100 150 200]
 [ 50 100 150]
 [  0  50 100]]

--- Матриця ефекту E ---
[[20 30 40]
 [10 20 30]
 [ 5 10 15]]


=== 1. Зміна контрасту (M * 0.5) ===
[[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]


=== 2. Корекція яскравості (M + 25) ===
[[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]


=== 3. Змішування (0.8*M + 0.2*E) ===
[[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]


**Завдання №2. Пошук схожих фільмів (аналітичний розв'язок)**

Є профіль користувача — це вектор інтересів до жанрів [Action, Comedy, Drama].

Також є три фільми $A$, $B$, $C$ кожен з яких має таку ж структуру характеристик.

Вектор профілю користувача: $\vec{u}=(8,2,5)$.

Та три фільми:

*   Фільм А (Action movie): $\vec{v}_{A}=(9, 1, 2)$
*   Фільм B (Comedy movie): $\vec{v}_{B}=(1, 9, 8)$
*   Фільм C (Drama movie): $\vec{v}_{C}=(7, 2, 6)$

Аналітична частина розв'язку:


1.   Обчисліть аналітично норму вектора користувача ∥u∥.
2.   Обчисліть схожість (similarity score) профілю користувача з кожним із трьох фільмів.
3.   Порівняйте отримані значення та визначте, який фільм має найвищий бал схожості.

- - -
**Рішення:**
1. Обчислемо аналітично норму вектора користувача $\|\mathbf{u}\|$:
$$ \|\mathbf{u}\|=\sqrt{8^2+2^2+5^2}=\sqrt {64+4+25}=\sqrt {93} $$

2. Обчислюємо схожесті з кожним фільмом:

    2.1. Фільм А (Action): $\vec{v}_{A}=(9, 1, 2)$
      *   Скалярний добуток:
      $$ {u}⋅\vec{v}_{A}=8 ⋅9+2⋅1+5⋅2=72+2+10=84
      $$
      * Норма вектора А
      $$ \||\mathbf{\vec{v}_{A}}\||=\sqrt{9^2+1^2+2^2}=\sqrt {81+1+4}=\sqrt {86}
      $$
      * Схожість (А)
      $$ sim_{A}=\frac{84}{\sqrt{93} ⋅\sqrt {86}} \approx \frac{84}{89.44}≈0.939
      $$
    2.2. Фільм B (Comedy): $\vec{v}_{B}=(1, 9, 8)$
      *   Скалярний добуток:
      $$ {u}⋅\vec{v}_{B}=8⋅1+2⋅9+5⋅8=8+18+40=66
      $$
      * Норма вектора B
      $$ \||\mathbf{\vec {v}_{B}}\||=\sqrt{1^2+9^2+8^2}=\sqrt {1+81+64}=\sqrt {146}
      $$
      * Схожість (B)
      $$ sim_{B}=\frac{66}{\sqrt{93} ⋅\sqrt {146}} \approx \frac{66}{116.53}≈0.566
      $$
      2.3. Фільм C (Drama): $\vec{v}_{C}=(7, 2, 6)$
      *   Скалярний добуток:
      $$ {u}⋅ \vec{v}_{C}=8⋅7+2⋅2+5⋅6=56+4+30=90
      $$
      * Норма вектора C
      $$ \||\mathbf{\vec {v}_{C}}\||=\sqrt{7^2+2^2+6^2}=\sqrt {49+4+36}=\sqrt {89}
      $$
      * Схожість (C)
      $$ sim_{C}=\frac{90}{\sqrt{93} ⋅\sqrt {89}} \approx \frac{90}{90.98}≈0.989
      $$

3. Порівняння та висновки:

  Порівняємо отримані значення схожості:
* Фільм А: 0.939
* Фільм B: 0.566
* Фільм C: 0.989

**Відповідь:**

Найбільшу схожість має  Фільм С (Drama) та цей фільм найкраще відповідає профілю інтересів користувача.

- - -


In [ ]:
# Завдання 2. Пошук схожих фільмів
# Програмна реалізація

import numpy as np
# Задаємо вектори
# Вектор користувача
u=np.array(8, 2, 5)
# Фільм А
v_A=np.array ([9, 1, 2])
# Фільм В
v_B=np.array ([1, 9, 8])
# Фільм С
v_C=np.array ([7, 2, 6])

# Обчислюємо норму ветора користувача
norm_u=np.linalg.norm(u)
print (f"Норма вектора кристувача ||u||:{norm_u: .4f}")

# Функція для розрахунку косінусної схожості
def cosine_similarity (vec1, vec2):
  dot_product=np.dot (vec1, vec2)
  norm1=np.linalg.norm (vec1)
  norm2=np.linalg.norm (vec2)
  return dot_product/(norm1*norm2)

# Обчислюємо схожість для кожного фільму
similarity_A=cosine_similarity (u, v_A)
similarity_B=cosine_similarity (u, v_B)
similarity_C=cosine_similarity (u, v_C)
print (f"Косінусна схожість з фільмом А: {similarity_A: .3f}")
print (f"Косінусна схожість з фільмом В: {similarity_B: .3f}")
print (f"Косінусна схожість з фільмом С: {similarity_C: .3f}")
# Визначаємо найбільш схожий фільм
similarities={'A': similarity_A, 'B': similarity_B, 'C': similarity_C}
most_similar_film=max (similarities, key=similarities.get)
print (f"Найбільш схожий фільм: {most_similar_film}")
---

In [ ]:
# Завдання 3. Аналіз виробництва
# Програмна реалізація

import numpy as np
# Матриця витрат А
# Рядки: мотори, контролери, акумулятори
# Стовпці: х1 (розвідник), х2 (камікадзе), х3 (вантажний)
A = np.array ([
    [4, 4, 6], # мотори
    [1, 1, 2], # контролери
    [1, 2, 4]  # акумулятори
], dtype=float)

# Вектор загальних витрат b
b = np.array ([
    460, # мотори
    130, # контролери
    240  # акумулятори
    ], dtype=float)

# Перевірка, чи існує єдиний розв'язок
det_A = np.linalg.det(A)
if det_A == 0:
    print("Система не має єдиного розв'язку.")
else:
# Розв'язання системи рівнянь Ax = b
    x = np.linalg.solve(A, b)
    print("Оптимальний випуск дронів:")
    print(f"Розвідники (x1): {int(x[0])}")
    print(f"Камікадзе (x2): {int(x[1])}")
    print(f"Вантажні (x3): {int(x[2])}")
    # Перевірка правильності розв'язку
    b_check=A@x
    print("\nПеревірка (Ax*b):")
    print(b_check)

- - -

In [ ]:
# Завдання 4. Прогноз тренду
# Програмна реалізація

import numpy as np

# Дані
t = np.array([1, 2, 3, 4, 5])
y = np.array([22, 28, 37, 45, 53])

# Формуємо матрицю A
A = np.column_stack((t, np.ones(len(t))))

# Красивий вивід матриці A
print("Матриця A:")
print("-" * 22)
for row in A:
    print(f"{int(row[0]):>4} | {int(row[1]):>1}")
print("-" * 22)

# МНК
k, b = np.linalg.lstsq(A, y, rcond=None)[0]

# Прогноз
y_pred = k * 6 + b

# Красивий вивід коефіцієнтів
print("\nКоефіцієнти лінійної регресії:")
print("-" * 30)
print(f"k (нахил прямої)     = {k:8.2f}")
print(f"b (вільний член)     = {b:8.2f}")
print("-" * 30)

# Результат
print(f"\nРівняння тренду:")
print(f"y = {k:.2f}·x + {b:.2f}")

print(f"\nПрогноз на 6-ту годину:")
print(f"ŷ(6) = {y_pred:.2f}")